---
name: Pre-Release

# Workflow name based on selected inputs. Fallback to default Github naming when expression evaluates to empty string
run-name: >-
  ${{
    inputs.prerelease && inputs.test && format('Build {0} ➤ Test ➤ Publish to NPM', github.ref_name)  ||
    inputs.prerelease && !inputs.test && format('Build {0} ➤ Skip Tests ➤ Publish pre release to NPM', github.ref_name) ||
    github.event_name == 'workflow_dispatch' && inputs.test && format('Build {0} ➤ Test', github.ref_name) ||
    github.event_name == 'workflow_dispatch' && !inputs.test && format('Build {0} ➤ Skip Tests', github.ref_name) ||
    ''
  }}

on:
  workflow_dispatch:
    inputs:
      # test:
      #   description: Run tests
      #   required: true
      #   default: true
      #   type: boolean
      prerelease:
        description: create new pre release
        required: true
        default: false
        type: boolean

concurrency:
  # On PRs builds will cancel if new pushes happen before the CI completes, as it defines `github.head_ref` and gives it the name of the branch the PR wants to merge into
  # Otherwise `github.run_id` ensures that you can quickly merge a queue of PRs without causing tests to auto cancel on any of the commits pushed to main.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: yarn install --frozen-lockfile
        # Linting can be skipped
      - run: yarn lint
        # if: github.event.inputs.test != 'false'
        # But not the build script, as semantic-release will crash if this command fails so it makes sense to test it early
      - run: yarn prepublishOnly --if-present

  # Will add when I add tests
  # test:
  #   needs: build
  #   # The test matrix can be skipped, in case a new release needs to be fast-tracked and tests are already passing on main
  #   if: github.event.inputs.test != 'false'
  #   runs-on: ${{ matrix.os }}
  #   name: Node.js ${{ matrix.node }} / ${{ matrix.os }}
  #   strategy:
  #     # A test failing on windows doesn't mean it'll fail on macos. It's useful to let all tests run to its completion to get the full picture
  #     fail-fast: false
  #     matrix:
  #       # Run the testing suite on each major OS with the latest LTS release of Node.js
  #       os: [macos-latest, ubuntu-latest, windows-latest]
  #       node: [lts/*]
  #       # It makes sense to also test the oldest, and latest, versions of Node.js, on ubuntu-only since it's the fastest CI runner
  #       include:
  #         - os: ubuntu-latest
  #           # Test the oldest LTS release of Node that's still receiving bugfixes and security patches, versions older than that have reached End-of-Life
  #           node: lts/-1
  #         - os: ubuntu-latest
  #           # Test the actively developed version that will become the latest LTS release next October
  #           node: current
  #   steps:
  #     # It's only necessary to do this for windows, as mac and ubuntu are sane OS's that already use LF
  #     - name: Set git to use LF
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         git config --global core.autocrlf false
  #         git config --global core.eol lf
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: npm
  #         node-version: ${{ matrix.node }}
  #     - run: yarn install
  #     - run: npm test --if-present

  release:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
    needs: [build]
    # only run if opt-in during workflow_dispatch
    # add back in && needs.test.result != 'failure' && needs.test.result != 'cancelled'
    if: always() && github.event.inputs.prerelease == 'true' && needs.build.result != 'failure'
    runs-on: ubuntu-latest
    name: Semantic release
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.ECOSPARK_APP_ID }}
          private-key: ${{ secrets.ECOSPARK_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          # Need to fetch entire commit history to
          # analyze every commit since last release
          fetch-depth: 0
          # Uses generated token to allow pushing commits back
          token: ${{ steps.app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - run: yarn install --frozen-lockfile
      - run: npm audit signatures
        # set current branch 
      - run: echo '{"extends": "@sanity/semantic-release-preset","branches": ["main", {"name": "canary", "prerelease": true}, {“name”: "'${{github.ref_name}}'", “prerelease”: true}]}' > .releaserc.json && npx semantic-release
        # Don't allow interrupting the release step if the job is cancelled, as it can lead to an inconsistent state
        # e.g. git tags were pushed but it exited before `npm publish`
        if: always()
        env:
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
